global using System.Diagnostics;
global using System.Globalization;
global using System.IO.Compression;
global using System.Net;
global using System.Runtime.InteropServices;
global using System.Runtime.Serialization;
global using System.Text;
global using System.Text.Json;
global using System.Text.RegularExpressions;
